"""empty message

Revision ID: 1aebf13af999
Revises: 46c600066278
Create Date: 2018-04-21 21:55:43.996000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aebf13af999'
down_revision = '46c600066278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CarsDataset',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('vehicleType', sa.Text(), nullable=True),
    sa.Column('yearOfRegistration', sa.Integer(), nullable=True),
    sa.Column('gearbox', sa.Text(), nullable=True),
    sa.Column('kilometer', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('bluetooth', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Bdatetime', sa.Text(), nullable=True),
    sa.Column('Bday', sa.Text(), nullable=True),
    sa.Column('Btime', sa.Text(), nullable=True),
    sa.Column('Rdatetime', sa.Text(), nullable=True),
    sa.Column('Rday', sa.Text(), nullable=True),
    sa.Column('Rtime', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CarsDataset')
    # ### end Alembic commands ###
