"""empty message

Revision ID: 68c54f12ad2a
Revises: f2edf1641917
Create Date: 2018-04-19 11:03:43.003000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c54f12ad2a'
down_revision = 'f2edf1641917'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('Bdatetime', sa.Text(), nullable=False),
    sa.Column('Bday', sa.Text(), nullable=False),
    sa.Column('Btime', sa.Text(), nullable=False),
    sa.Column('Rdatetime', sa.Text(), nullable=False),
    sa.Column('Rday', sa.Text(), nullable=False),
    sa.Column('Rtime', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('cattype', sa.String(length=100), nullable=False),
    sa.Column('gearbox', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CarsDataset',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('vehicleType', sa.Text(), nullable=True),
    sa.Column('yearOfRegistration', sa.Integer(), nullable=True),
    sa.Column('gearbox', sa.Text(), nullable=True),
    sa.Column('kilometer', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('bluetooth', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CarsDataset')
    op.drop_table('Cars')
    # ### end Alembic commands ###
