"""empty message

Revision ID: dc7af681579e
Revises: 58be86e761ad
Create Date: 2018-04-29 12:50:08.971000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc7af681579e'
down_revision = '58be86e761ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carname', sa.Text(), nullable=True),
    sa.Column('Bdatetime', sa.Text(), nullable=True),
    sa.Column('Bday', sa.Text(), nullable=True),
    sa.Column('Btime', sa.Text(), nullable=True),
    sa.Column('Rdatetime', sa.Text(), nullable=True),
    sa.Column('Rday', sa.Text(), nullable=True),
    sa.Column('Rtime', sa.Text(), nullable=True),
    sa.Column('price', sa.Text(), nullable=True),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('cattype', sa.String(length=100), nullable=True),
    sa.Column('gearbox', sa.String(length=100), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CarsDataset',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('vehicleType', sa.Text(), nullable=True),
    sa.Column('yearOfRegistration', sa.Integer(), nullable=True),
    sa.Column('gearbox', sa.Text(), nullable=True),
    sa.Column('kilometer', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('bluetooth', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CarsDataset')
    op.drop_table('Cars')
    # ### end Alembic commands ###
