"""empty message

Revision ID: e2c6682b6b22
Revises: c4ba1c4bea57
Create Date: 2018-04-18 17:30:55.289000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2c6682b6b22'
down_revision = 'c4ba1c4bea57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('Bdatetime', sa.Text(), nullable=False),
    sa.Column('Bday', sa.Text(), nullable=False),
    sa.Column('Btime', sa.Text(), nullable=False),
    sa.Column('Rdatetime', sa.Text(), nullable=False),
    sa.Column('Rday', sa.Text(), nullable=False),
    sa.Column('Rtime', sa.Text(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('cattype', sa.String(length=100), nullable=False),
    sa.Column('gearbox', sa.String(length=100), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('CarsDataset',
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('vehicleType', sa.Text(), nullable=True),
    sa.Column('yearOfRegistration', sa.Integer(), nullable=True),
    sa.Column('gearbox', sa.Text(), nullable=True),
    sa.Column('kilometer', sa.Integer(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('lng', sa.FLOAT(), nullable=True),
    sa.Column('lat', sa.FLOAT(), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('bluetooth', sa.Text(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('cars')
    op.drop_table('carsdataset')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carsdataset',
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('price', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('vehicleType', mysql.TEXT(), nullable=False),
    sa.Column('yearOfRegistration', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('gearbox', mysql.TEXT(), nullable=False),
    sa.Column('kilometer', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('brand', mysql.TEXT(), nullable=False),
    sa.Column('lng', mysql.FLOAT(), nullable=False),
    sa.Column('lat', mysql.FLOAT(), nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], [u'user.id'], name=u'carsdataset_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('cars',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('Bdatetime', mysql.TEXT(), nullable=False),
    sa.Column('Bday', mysql.TEXT(), nullable=False),
    sa.Column('Btime', mysql.TEXT(), nullable=False),
    sa.Column('Rdatetime', mysql.TEXT(), nullable=False),
    sa.Column('Rday', mysql.TEXT(), nullable=False),
    sa.Column('Rtime', mysql.TEXT(), nullable=False),
    sa.Column('create_time', mysql.DATETIME(), nullable=True),
    sa.Column('cattype', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('gearbox', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('author_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['author_id'], [u'user.id'], name=u'cars_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('CarsDataset')
    op.drop_table('Cars')
    # ### end Alembic commands ###
